[env]
# supports arbitrary env vars so rtx can be used like direnv/dotenv
GO_ENV = 'GOLANG_RTX'
RTX_DEBUG=true
RTX_USE_TOML=true #Set to 1 to default to using .rtx.toml
RTX_LOG_FILE='./rtx.log' #Output logs to a file.

RTX_VERBOSE='1'  #This shows the installation output during rtx install and rtx plugin install.
[tools]
golang = '1.21.4'
protoc = '25.1'
[settings]


verbose = true     # set true to see full installation output
jobs = 4            # number of plugins or runtimes to install in parallel. The default is `4`.
yes = true         # set to true to automatically answer yes to all prompts
experimental = false # enable experimental features
log_level = 'debug'  # log verbosity
[plugins]
golang = 'https://github.com/rtx-plugins/rtx-golang'
protoc = 'https://github.com/paxosglobal/asdf-protoc.git'

