// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: brokerevent/brokerevent.proto

package borkerevent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Name int32

const (
	Name_createUser Name = 0
)

// Enum value maps for Name.
var (
	Name_name = map[int32]string{
		0: "createUser",
	}
	Name_value = map[string]int32{
		"createUser": 0,
	}
)

func (x Name) Enum() *Name {
	p := new(Name)
	*p = x
	return p
}

func (x Name) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Name) Descriptor() protoreflect.EnumDescriptor {
	return file_brokerevent_brokerevent_proto_enumTypes[0].Descriptor()
}

func (Name) Type() protoreflect.EnumType {
	return &file_brokerevent_brokerevent_proto_enumTypes[0]
}

func (x Name) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Name.Descriptor instead.
func (Name) EnumDescriptor() ([]byte, []int) {
	return file_brokerevent_brokerevent_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   Name                   `protobuf:"varint,2,opt,name=name,proto3,enum=borkerevent.Name" json:"name,omitempty"`
	Source string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Time   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*Task_Fake
	Payload isTask_Payload `protobuf_oneof:"Payload"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brokerevent_brokerevent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_brokerevent_brokerevent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_brokerevent_brokerevent_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() Name {
	if x != nil {
		return x.Name
	}
	return Name_createUser
}

func (x *Task) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Task) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (m *Task) GetPayload() isTask_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Task) GetFake() *FakeMessage {
	if x, ok := x.GetPayload().(*Task_Fake); ok {
		return x.Fake
	}
	return nil
}

type isTask_Payload interface {
	isTask_Payload()
}

type Task_Fake struct {
	Fake *FakeMessage `protobuf:"bytes,100,opt,name=fake,proto3,oneof"`
}

func (*Task_Fake) isTask_Payload() {}

type FakeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FakeMessage) Reset() {
	*x = FakeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brokerevent_brokerevent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FakeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeMessage) ProtoMessage() {}

func (x *FakeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_brokerevent_brokerevent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeMessage.ProtoReflect.Descriptor instead.
func (*FakeMessage) Descriptor() ([]byte, []int) {
	return file_brokerevent_brokerevent_proto_rawDescGZIP(), []int{1}
}

func (x *FakeMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FakeMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_brokerevent_brokerevent_proto protoreflect.FileDescriptor

var file_brokerevent_brokerevent_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x62, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc0, 0x01,
	0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x62, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x66, 0x61, 0x6b, 0x65, 0x18, 0x64, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x46, 0x61, 0x6b, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x04, 0x66, 0x61, 0x6b, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x31, 0x0a, 0x0b, 0x46, 0x61, 0x6b, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x2a, 0x16, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x10, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x6d, 0x75, 0x73, 0x68,
	0x71, 0x2f, 0x6f, 0x72, 0x6d, 0x75, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2f, 0x67, 0x6f, 0x2f, 0x62, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_brokerevent_brokerevent_proto_rawDescOnce sync.Once
	file_brokerevent_brokerevent_proto_rawDescData = file_brokerevent_brokerevent_proto_rawDesc
)

func file_brokerevent_brokerevent_proto_rawDescGZIP() []byte {
	file_brokerevent_brokerevent_proto_rawDescOnce.Do(func() {
		file_brokerevent_brokerevent_proto_rawDescData = protoimpl.X.CompressGZIP(file_brokerevent_brokerevent_proto_rawDescData)
	})
	return file_brokerevent_brokerevent_proto_rawDescData
}

var file_brokerevent_brokerevent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_brokerevent_brokerevent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_brokerevent_brokerevent_proto_goTypes = []any{
	(Name)(0),                     // 0: borkerevent.Name
	(*Task)(nil),                  // 1: borkerevent.Task
	(*FakeMessage)(nil),           // 2: borkerevent.FakeMessage
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_brokerevent_brokerevent_proto_depIdxs = []int32{
	0, // 0: borkerevent.Task.name:type_name -> borkerevent.Name
	3, // 1: borkerevent.Task.time:type_name -> google.protobuf.Timestamp
	2, // 2: borkerevent.Task.fake:type_name -> borkerevent.FakeMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_brokerevent_brokerevent_proto_init() }
func file_brokerevent_brokerevent_proto_init() {
	if File_brokerevent_brokerevent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_brokerevent_brokerevent_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brokerevent_brokerevent_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FakeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_brokerevent_brokerevent_proto_msgTypes[0].OneofWrappers = []any{
		(*Task_Fake)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brokerevent_brokerevent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brokerevent_brokerevent_proto_goTypes,
		DependencyIndexes: file_brokerevent_brokerevent_proto_depIdxs,
		EnumInfos:         file_brokerevent_brokerevent_proto_enumTypes,
		MessageInfos:      file_brokerevent_brokerevent_proto_msgTypes,
	}.Build()
	File_brokerevent_brokerevent_proto = out.File
	file_brokerevent_brokerevent_proto_rawDesc = nil
	file_brokerevent_brokerevent_proto_goTypes = nil
	file_brokerevent_brokerevent_proto_depIdxs = nil
}
