version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management console port
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Default username
      RABBITMQ_DEFAULT_PASS: guest  # Default password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist data

volumes:
  rabbitmq_data: