// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: writekey.proto

package writekey

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteKeyStatus int32

const (
	WriteKeyStatus_INACTIVE WriteKeyStatus = 0
	WriteKeyStatus_ACTIVE   WriteKeyStatus = 1
)

// Enum value maps for WriteKeyStatus.
var (
	WriteKeyStatus_name = map[int32]string{
		0: "INACTIVE",
		1: "ACTIVE",
	}
	WriteKeyStatus_value = map[string]int32{
		"INACTIVE": 0,
		"ACTIVE":   1,
	}
)

func (x WriteKeyStatus) Enum() *WriteKeyStatus {
	p := new(WriteKeyStatus)
	*p = x
	return p
}

func (x WriteKeyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteKeyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_writekey_proto_enumTypes[0].Descriptor()
}

func (WriteKeyStatus) Type() protoreflect.EnumType {
	return &file_writekey_proto_enumTypes[0]
}

func (x WriteKeyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteKeyStatus.Descriptor instead.
func (WriteKeyStatus) EnumDescriptor() ([]byte, []int) {
	return file_writekey_proto_rawDescGZIP(), []int{0}
}

type WriteKeyMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WriteKey   string               `protobuf:"bytes,1,opt,name=write_key,json=writeKey,proto3" json:"write_key,omitempty"`
	OwnerId    string               `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	SourceId   string               `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	CreatedAt  *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	Status     WriteKeyStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=writekey.WriteKeyStatus" json:"status,omitempty"`
}

func (x *WriteKeyMetaData) Reset() {
	*x = WriteKeyMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_writekey_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteKeyMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteKeyMetaData) ProtoMessage() {}

func (x *WriteKeyMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_writekey_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteKeyMetaData.ProtoReflect.Descriptor instead.
func (*WriteKeyMetaData) Descriptor() ([]byte, []int) {
	return file_writekey_proto_rawDescGZIP(), []int{0}
}

func (x *WriteKeyMetaData) GetWriteKey() string {
	if x != nil {
		return x.WriteKey
	}
	return ""
}

func (x *WriteKeyMetaData) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *WriteKeyMetaData) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *WriteKeyMetaData) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WriteKeyMetaData) GetLastUsedAt() *timestamp.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *WriteKeyMetaData) GetStatus() WriteKeyStatus {
	if x != nil {
		return x.Status
	}
	return WriteKeyStatus_INACTIVE
}

type GetWriteKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WriteKey string `protobuf:"bytes,1,opt,name=write_key,json=writeKey,proto3" json:"write_key,omitempty"`
}

func (x *GetWriteKeyRequest) Reset() {
	*x = GetWriteKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_writekey_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWriteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWriteKeyRequest) ProtoMessage() {}

func (x *GetWriteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_writekey_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWriteKeyRequest.ProtoReflect.Descriptor instead.
func (*GetWriteKeyRequest) Descriptor() ([]byte, []int) {
	return file_writekey_proto_rawDescGZIP(), []int{1}
}

func (x *GetWriteKeyRequest) GetWriteKey() string {
	if x != nil {
		return x.WriteKey
	}
	return ""
}

type GetWriteKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *WriteKeyMetaData `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *GetWriteKeyResponse) Reset() {
	*x = GetWriteKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_writekey_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWriteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWriteKeyResponse) ProtoMessage() {}

func (x *GetWriteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_writekey_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWriteKeyResponse.ProtoReflect.Descriptor instead.
func (*GetWriteKeyResponse) Descriptor() ([]byte, []int) {
	return file_writekey_proto_rawDescGZIP(), []int{2}
}

func (x *GetWriteKeyResponse) GetMetadata() *WriteKeyMetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_writekey_proto protoreflect.FileDescriptor

var file_writekey_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x6b, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x77, 0x72, 0x69, 0x74, 0x65, 0x6b, 0x65, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x02, 0x0a, 0x10,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1b, 0x0a, 0x09, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x72, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x3c, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x64, 0x41, 0x74, 0x12, 0x30,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18,
	0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x6b, 0x65, 0x79, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x31, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x22, 0x4d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x6b, 0x65, 0x79, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2a, 0x2a, 0x0a, 0x0e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x32, 0x5d,
	0x0a, 0x0f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x12, 0x4a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x1c, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x6b, 0x65, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x6b, 0x65, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x45, 0x5a,
	0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x6d, 0x75,
	0x73, 0x68, 0x71, 0x2f, 0x6f, 0x72, 0x6d, 0x75, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x6b, 0x65, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_writekey_proto_rawDescOnce sync.Once
	file_writekey_proto_rawDescData = file_writekey_proto_rawDesc
)

func file_writekey_proto_rawDescGZIP() []byte {
	file_writekey_proto_rawDescOnce.Do(func() {
		file_writekey_proto_rawDescData = protoimpl.X.CompressGZIP(file_writekey_proto_rawDescData)
	})
	return file_writekey_proto_rawDescData
}

var file_writekey_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_writekey_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_writekey_proto_goTypes = []any{
	(WriteKeyStatus)(0),         // 0: writekey.WriteKeyStatus
	(*WriteKeyMetaData)(nil),    // 1: writekey.WriteKeyMetaData
	(*GetWriteKeyRequest)(nil),  // 2: writekey.GetWriteKeyRequest
	(*GetWriteKeyResponse)(nil), // 3: writekey.GetWriteKeyResponse
	(*timestamp.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_writekey_proto_depIdxs = []int32{
	4, // 0: writekey.WriteKeyMetaData.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: writekey.WriteKeyMetaData.last_used_at:type_name -> google.protobuf.Timestamp
	0, // 2: writekey.WriteKeyMetaData.status:type_name -> writekey.WriteKeyStatus
	1, // 3: writekey.GetWriteKeyResponse.metadata:type_name -> writekey.WriteKeyMetaData
	2, // 4: writekey.WriteKeyManager.GetWriteKey:input_type -> writekey.GetWriteKeyRequest
	3, // 5: writekey.WriteKeyManager.GetWriteKey:output_type -> writekey.GetWriteKeyResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_writekey_proto_init() }
func file_writekey_proto_init() {
	if File_writekey_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_writekey_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WriteKeyMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_writekey_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetWriteKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_writekey_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetWriteKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_writekey_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_writekey_proto_goTypes,
		DependencyIndexes: file_writekey_proto_depIdxs,
		EnumInfos:         file_writekey_proto_enumTypes,
		MessageInfos:      file_writekey_proto_msgTypes,
	}.Build()
	File_writekey_proto = out.File
	file_writekey_proto_rawDesc = nil
	file_writekey_proto_goTypes = nil
	file_writekey_proto_depIdxs = nil
}
