// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.6.1
// source: destination/destination.proto

package destination

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveredEvent) Reset() {
	*x = DeliveredEvent{}
	mi := &file_destination_destination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveredEvent) ProtoMessage() {}

func (x *DeliveredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_destination_destination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveredEvent.ProtoReflect.Descriptor instead.
func (*DeliveredEvent) Descriptor() ([]byte, []int) {
	return file_destination_destination_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveredEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type DeliveredEventsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*DeliveredEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveredEventsList) Reset() {
	*x = DeliveredEventsList{}
	mi := &file_destination_destination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveredEventsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveredEventsList) ProtoMessage() {}

func (x *DeliveredEventsList) ProtoReflect() protoreflect.Message {
	mi := &file_destination_destination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveredEventsList.ProtoReflect.Descriptor instead.
func (*DeliveredEventsList) Descriptor() ([]byte, []int) {
	return file_destination_destination_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveredEventsList) GetEvents() []*DeliveredEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_destination_destination_proto protoreflect.FileDescriptor

var file_destination_destination_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a,
	0x0e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x4a,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x6d, 0x75, 0x73, 0x68, 0x71,
	0x2f, 0x6f, 0x72, 0x6d, 0x75, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f,
	0x67, 0x6f, 0x2f, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_destination_destination_proto_rawDescOnce sync.Once
	file_destination_destination_proto_rawDescData []byte
)

func file_destination_destination_proto_rawDescGZIP() []byte {
	file_destination_destination_proto_rawDescOnce.Do(func() {
		file_destination_destination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_destination_destination_proto_rawDesc), len(file_destination_destination_proto_rawDesc)))
	})
	return file_destination_destination_proto_rawDescData
}

var file_destination_destination_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_destination_destination_proto_goTypes = []any{
	(*DeliveredEvent)(nil),      // 0: destination.DeliveredEvent
	(*DeliveredEventsList)(nil), // 1: destination.DeliveredEventsList
}
var file_destination_destination_proto_depIdxs = []int32{
	0, // 0: destination.DeliveredEventsList.events:type_name -> destination.DeliveredEvent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_destination_destination_proto_init() }
func file_destination_destination_proto_init() {
	if File_destination_destination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_destination_destination_proto_rawDesc), len(file_destination_destination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_destination_destination_proto_goTypes,
		DependencyIndexes: file_destination_destination_proto_depIdxs,
		MessageInfos:      file_destination_destination_proto_msgTypes,
	}.Build()
	File_destination_destination_proto = out.File
	file_destination_destination_proto_goTypes = nil
	file_destination_destination_proto_depIdxs = nil
}
