type: yml

source:
  http_server:
    port: 8090
    network: "tcp"
redis:
  port: 6379
  host: localhost
  db: 0
  password: ""
etcd:
  port: 2379
  host: localhost
  dial_timeout: 5
destination:
  debug_mode: true
  consumer_topic: "pe.#"    # pe stands for processed event. and # substitute for zero or more words.
  rabbitmq_consumer_connection:
    user: guest
    password: guest
    host: localhost
    port: 5672
    vhost:
    reconnect_second: 5
  rabbitmq_task_manager_connection:
      user: guest
      password: guest
      host: localhost
      port: 5672
  redis_task_idempotency:
    port: 6379
    host: localhost
    db: 0
    password: ""
    prefix: "destination-task-status::"
    expiration: 0

manager:
  broker_config:
    channel_size: 100
    number_instant: 5
    max_retry_policy: 5
  jwt_config:
    secret_key: "Ormus_jwt"
    access_expiration_time_in_day: 7
    refresh_expiration_time_in_day: 28
    access_subject: "ac"
    refresh_subject: "rt"


